### ISSUE TITLE
not able to write text containing characters like € in PDF

### ISSUE THREAD

**Issue by rupeshsasne** [TomRoush/PdfBox-Android#40] opened 2015-05-04 11:39 UTC
I was trying to write string `500 €/year**` as follows,

```
pageContentStream.drawString("500 " + Html.fromHtml(getString(R.string.euro)).toString() + "/hour");
```

where `euro` is defined in `strings.xml` as 

```
<string name="euro">(&#8364;)</string>
<string name="pound">(&#163;)</string>
```

With above code it is writing some gibberish characters.

I found one solution [here](http://stackoverflow.com/a/22274334) to write `€`, which is working perfectly. 

I want to write whole text in one go, is it possible?

Or do I need to write `€` first, then move text next to it and then write remaining text? 

I don't feel that would be a `correct` solution.

**Comment by Birdbrain2** [comment] 2015-05-05 04:42
For now, writing and moving seems to be the best solution, though it's certainly inconvenient. I'll look and see if a fix has already been made to address this. If one hasn't we'll either have to wait until it is fixed or I'll see what I can do to make one.

**Comment by TomRoush** [comment] 2016-12-27 03:52
[Resolved JIRA issue.](https://issues.apache.org/jira/browse/PDFBOX-1242) This will be fixed when the codebase gets updated to v2.0.0.

**Comment by frankyxcs** [comment] 2017-08-14 03:57
Hi i have the same problem that the app crashes while writing € and other here

 Caused by: java.lang.IllegalArgumentException: This font type only supports 8-bit code points
                                                                         at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:317)
                                                                         at com.tom_roush.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:264)
                                                                         at com.tom_roush.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:293)


Is there maybe any fix available ?

**Comment by frankyxcs** [comment] 2017-08-23 20:04
I have fixed the annoying problem with the included font so € and others are working now . 

 AssetManager assetManager = this.getAssets();
            PDFont pdfFont = PDType0Font.load(doc, assetManager.open("com/tom_roush/pdfbox/resources/ttf/LiberationSans-Regular.ttf"));

**Closed** 2021-07-06 00:39 UTC
Labels: type: bug
