### ISSUE TITLE
Merge PDFs produces blank pages

### ISSUE THREAD

**Issue by robbyl** [TomRoush/PdfBox-Android#155] opened 2018-04-28 11:17 UTC
Merge PDFs produces blank pages for version v1.8.10.0 but the older version v1.8.9.1 works fine. Please see attached sample PDFs
[huge pdf-Page11.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957648/huge.pdf-Page11.pdf)
[huge pdf-Page12.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957649/huge.pdf-Page12.pdf)
[huge pdf-Page13.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957650/huge.pdf-Page13.pdf)
[huge pdf-Page14.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957651/huge.pdf-Page14.pdf)

**Comment by TomRoush** [comment] 2018-05-14 23:18
Possible duplicate of #130 and #133.

**Comment by markfried96** [comment] 2018-08-15 12:30
I have the same problem.. Are there any updates since April?

**Comment by TomRoush** [comment] 2019-04-18 01:13
The issue has been fixed in the develop-2.0 branch and the fix will be available with the 2.0 release.

**Comment by TomRoush** [comment] 2021-07-20 02:59
Closing as 2.0.0.0 is now released

**Closed by TomRoush** 2021-07-20 02:59 UTC
Labels: type: bug
