### ISSUE TITLE
Using specific fonts

### ISSUE THREAD

**Issue by EathanHunt** [TomRoush/PdfBox-Android#135] opened 2017-11-28 10:14 UTC
I am using pdfbox for an application, the fontbox package is using too much space, is there a way to reduce the number of imported fonts.

**Comment by TomRoush** [comment] 2017-12-24 19:30
Duplicate of #103. In short, If you know what kinds of encoding will be used in the PDFs you will be dealing with, you should be able to remove some of the FontBox resources for other encoding types.

**Closed by TomRoush** 2017-12-24 19:30 UTC
Labels: duplicate
